[28Nov 16:30:17] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[28Nov 17:23:29] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:29:17] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:29:25] WARNING [django.request:224] Not Found: /favicon.ico
[30Nov 13:30:24] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:30:25] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:37:53] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:37:54] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:41:45] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:41:46] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:42:39] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:42:40] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:42:44] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 25, in get_queryset
    print(trans)
NameError: name 'trans' is not defined
[30Nov 13:43:06] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:43:07] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:43:13] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 37, in get_queryset
    q_set = q_set.filter(transmission__icontains=trans-m)
NameError: name 'trans' is not defined
[30Nov 13:43:33] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:43:34] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:49:39] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:49:39] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 13:53:59] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 13:54:00] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:00:11] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:00:12] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:10:35] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:10:36] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:10:55] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 29, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:11:37] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:11:38] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:11:43] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:12:13] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:14:15] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:15:54] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:15:55] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:16:11] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:16:15] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:19:09] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:19:10] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:19:17] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 41, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 14:22:55] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:22:56] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:25:13] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:25:14] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:27:00] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:27:01] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:27:05] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:27:06] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:27:15] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    transmission.pop(trans)
TypeError: 'NoneType' object cannot be interpreted as an integer
[30Nov 14:28:18] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:28:19] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:28:36] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    transmission.pop(trans)
TypeError: 'NoneType' object cannot be interpreted as an integer
[30Nov 14:29:25] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:29:25] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:29:28] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 40, in get_queryset
    transmission.pop(trans)
TypeError: 'NoneType' object cannot be interpreted as an integer
[30Nov 14:29:47] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:29:48] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:29:51] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 41, in get_queryset
    transmission.pop(trans)
TypeError: 'NoneType' object cannot be interpreted as an integer
[30Nov 14:30:55] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:30:56] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:31:01] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 14:31:02] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 14:31:08] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 15:02:26] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 15:02:27] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 15:02:30] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 15:02:33] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[30Nov 15:04:07] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[30Nov 15:04:08] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[30Nov 15:04:18] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = q_set.filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1170, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
[01Dec 12:23:53] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:25:23] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:46:41] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:47:00] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 12:47:01] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:47:28] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:47:37] WARNING [django.request:224] Not Found: /favicon.ico
[01Dec 12:53:23] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 12:53:24] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:53:32] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 12:53:33] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:55:31] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 12:55:32] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:55:50] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 12:55:51] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 12:56:56] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 12:56:57] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:00:47] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:00:47] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:02:09] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:02:09] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:02:32] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 13:02:33] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:03:35] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 13:03:36] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:05:24] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:05:25] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:06:41] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 13:06:42] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:07:36] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 13:07:37] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:08:48] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:08:49] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:10:34] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\forms.py changed, reloading.
[01Dec 13:10:35] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:11:06] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:13:19] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:13:20] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:14:47] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:14:48] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:15:22] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:15:23] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:15:46] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:15:47] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[01Dec 13:15:54] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[01Dec 13:15:54] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 11:53:25] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 11:55:44] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 11:55:45] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 11:57:27] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 11:57:28] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 11:57:31] WARNING [django.request:224] Not Found: /
[02Dec 11:57:33] WARNING [django.request:224] Not Found: /favicon.ico
[02Dec 11:58:00] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 29, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'release_year' expected a number but got ''.
[02Dec 11:59:29] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 11:59:30] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 11:59:32] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 29, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'search' into field. Choices are: color, id, model, producer, release_year, transmission
[02Dec 12:00:33] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:00:34] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:06:26] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:06:27] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:06:54] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 30, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'release_year' expected a number but got ''.
[02Dec 12:10:37] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:10:38] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:10:44] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 30, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'search' into field. Choices are: color, id, model, producer, release_year, transmission
[02Dec 12:11:59] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 30, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'release_year' expected a number but got ''.
[02Dec 12:13:50] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:13:50] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:14:14] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:14:14] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:17:24] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:17:25] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:17:46] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:17:47] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:17:55] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:17:56] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:18:04] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 44, in get_queryset
    query *= Q(**{key: value})
TypeError: unsupported operand type(s) for *=: 'Q' and 'Q'
[02Dec 12:18:08] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 44, in get_queryset
    query *= Q(**{key: value})
TypeError: unsupported operand type(s) for *=: 'Q' and 'Q'
[02Dec 12:18:31] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:18:32] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:18:39] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'release_year' expected a number but got ''.
[02Dec 12:20:23] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:20:24] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:20:27] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'release_year' expected a number but got ''.
[02Dec 12:20:28] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1774, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: ''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 45, in get_queryset
    q_set = Car.objects.filter(query)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1319, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1165, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\lookups.py", line 76, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\fields\__init__.py", line 1776, in get_prep_value
    raise e.__class__(
ValueError: Field 'release_year' expected a number but got ''.
[02Dec 12:22:43] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:22:44] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:23:49] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:23:49] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:24:05] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:24:06] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:24:40] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:24:41] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:36:24] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:36:25] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:36:46] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:36:47] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:37:50] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:37:50] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:38:36] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:38:37] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:38:54] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:38:55] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:39:11] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:39:12] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:40:10] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:40:11] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:40:23] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:40:23] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:43:13] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:43:14] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:43:18] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:43:19] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
[02Dec 12:44:05] ERROR [django.request:224] Internal Server Error: /cars/
Traceback (most recent call last):
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\views\generic\list.py", line 142, in get
    self.object_list = self.get_queryset()
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py", line 30, in get_queryset
    q_set = Car.objects.filter(ww)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 942, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 962, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, *args, **kwargs)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\query.py", line 969, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1358, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1237, in build_filter
    return self._add_q(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1377, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1258, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1084, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\env\lib\site-packages\django\db\models\sql\query.py", line 1481, in names_to_path
    raise FieldError("Cannot resolve keyword '%s' into field. "
django.core.exceptions.FieldError: Cannot resolve keyword 'search' into field. Choices are: color, id, model, producer, release_year, transmission
[02Dec 12:44:59] INFO [django.utils.autoreload:236] C:\Aducation\SkillFactory\Python\Django-projects\Catalogue-search-django\cat_app\catalog\views.py changed, reloading.
[02Dec 12:45:00] INFO [django.utils.autoreload:613] Watching for file changes with StatReloader
